### ISSUE TITLE
error, Windows 11

### ISSUE THREAD

**Issue by and725rey** [metah4cker/deanonvoprosy#2]
exception Ошибка во время запуска клиента.
Traceback (most recent call last):
  File "C:\Users\ANDREW\Desktop\deanonvoprosy-main\deanon.py", line 173, in <module>
    app.run(main())
  File "C:\Users\ANDREW\AppData\Roaming\Python\Python312\site-packages\pyrogram\methods\utilities\run.py", line 77, in run
    run(coroutine)
  File "C:\Program Files\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\ANDREW\Desktop\deanonvoprosy-main\deanon.py", line 160, in main
    async with app:
  File "C:\Users\ANDREW\AppData\Roaming\Python\Python312\site-packages\pyrogram\client.py", line 311, in __aenter__
    return await self.start()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ANDREW\AppData\Roaming\Python\Python312\site-packages\pyrogram\methods\utilities\start.py", line 62, in start
    await self.authorize()
  File "C:\Users\ANDREW\AppData\Roaming\Python\Python312\site-packages\pyrogram\client.py", line 359, in authorize
    sent_code = await self.send_code(self.phone_number)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ANDREW\AppData\Roaming\Python\Python312\site-packages\pyrogram\methods\auth\send_code.py", line 79, in send_code
    return types.SentCode._parse(r)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ANDREW\AppData\Roaming\Python\Python312\site-packages\pyrogram\types\authorization\sent_code.py", line 58, in _parse
    type=enums.SentCodeType(type(sent_code.type)),
                                 ^^^^^^^^^^^^^^
AttributeError: 'BadMsgNotification' object has no attribute 'type'

**Comment by metah4cker** [comment]
Похоже, что ошибка на стороне фреймворка, который мы используем - **Pyrogram**. На данный момент, с этой проблемой уже сталкивались другие люди и программисты pyrogram пока что ничего не ответили. [Ссылка](https://github.com/pyrogram/pyrogram/issues/1374). Убедитесь, что вы ввели верные данные для входа (номер телефона, код). Возможно в этом и кроется вся суть проблемы.
