### ISSUE TITLE
Не работает просмотр в 3 боте

### ISSUE THREAD

**Issue by user555-github** [metah4cker/deanonvoprosy#4]
Выдаёт ошибку

**Comment by igortatarenko** [comment]
тоже самое 

`exception Ошибка во время работы скрипта.
Traceback (most recent call last):
  File "/Users/igortatarenko/Projects/deanonvoprosy/deanon.py", line 124, in deanon_2
    uid = json.loads(m.reply_markup.inline_keyboard[0][0].callback_data)['value']  # get user id, that wrote this message
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType`
